# Generated by Django 3.1.5 on 2021-02-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifycertify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraprofiledata',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
