# Generated by Django 3.1.5 on 2021-02-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifycertify', '0002_extraprofiledata_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraprofiledata',
            name='authLevel',
            field=models.CharField(choices=[(1, 'regular user'), (2, 'institute user'), (0, 'admin user')], max_length=1),
        ),
        migrations.AlterField(
            model_name='extraprofiledata',
            name='idproof',
            field=models.FileField(upload_to='media/'),
        ),
    ]
