# Generated by Django 3.1.5 on 2021-02-13 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('verifycertify', '0003_auto_20210206_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraprofiledata',
            name='id',
        ),
        migrations.AlterField(
            model_name='extraprofiledata',
            name='approved',
            field=models.CharField(choices=[(0, 'pending'), (1, 'approved'), (2, 'rejected')], default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='extraprofiledata',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
