# Generated by Django 3.1.5 on 2021-02-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifycertify', '0005_auto_20210213_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraprofiledata',
            name='authLevel',
            field=models.IntegerField(choices=[(1, 'regular user'), (2, 'institute user'), (0, 'admin user')], max_length=1),
        ),
    ]
