# Generated by Django 3.1.5 on 2021-02-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifycertify', '0007_neweventdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='neweventdata',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'approved')], default=0),
        ),
    ]
